### PR TITLE
Add signature

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Add signature closes https://github.com/tmds/Tmds.ExecFunction/issues/9

image

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
ping @tmds

**Comment by tmds** [comment]
I had missed this PR.
Thank you @MarcoRossignoli !

**Comment by tmds** [comment]
@MarcoRossignoli this is in v0.5.0 which is now on nuget.org.

**Comment by MarcoRossignoli** [comment]
thx!

**Pull request merged**
