### PR TITLE
Automatically attach debugger to subprocess

### PR DESCRIPTION
**Pull request by StratosBlue**
When reference package `Tmds.ExecFunction.VsDebugger` the subprocess will attach debugger automatically. 

Use conditional reference will avoid reference EnvDTE for release.
```C#
<ItemGroup Condition="'$(Configuration)' == 'Debug'">
  <ProjectReference Include="..\src\Tmds.ExecFunction.VsDebugger\Tmds.ExecFunction.VsDebugger.csproj" />
</ItemGroup>
```

### CODE REVIEW

**Comment by tmds** [comment]
@StratosBlue I missed this PR. The change looks good. Are you still available to address some feedback?

**Comment by StratosBlue** [comment]
@tmds Sure, with pleasure

**Comment by tmds** [comment]
style nit: instead of `var`, can you use the actual type? I'm following style similar to https://github.com/dotnet/runtime/blob/3537bf20373e2c6fd01d4e2d477be1b6d5be51d9/docs/coding-guidelines/coding-style.md?plain=1#L22-L23.

And, optional: it should be possible to include the dll from `Tmds.ExecFunction.VsDebugger` in the `Tmds.ExecFunction` package in a way that it gets included in the output only when `Configuration == Debug`. This can be done using a `targets` file. See https://stackoverflow.com/questions/60623546/targets-file-for-deploying-nativs-dlls-to-output-directory and similar.
If we can make that work, I'd prefer shipping it like that. I can also look into it myself when this is merged.

**Comment by StratosBlue** [comment]
@tmds Such a good idea. Let me try it.

**Comment by tmds** [comment]
We're moving in the right direction, but not there yet.
The nupkg doesn't contain `Tmds.ExecFunction.VsDebugger.dll`.
```
Archive:  Tmds.ExecFunction.0.5.1.nupkg
  inflating: _rels/.rels             
  inflating: Tmds.ExecFunction.nuspec  
  inflating: lib/netstandard2.0/Tmds.ExecFunction.dll  
  inflating: build/Tmds.ExecFunction.targets  
  inflating: [Content_Types].xml     
  inflating: package/services/metadata/core-properties/3e3e35d050a9476485e20ded17fc34b1.psmdcp  
```

**Comment by StratosBlue** [comment]
@tmds 
I checked it. When run `dotnet pack` directly. The `Tmds.ExecFunction.VsDebugger.dll` may not generated before generate package. A simple way to fix it is build before pack. Just like `dotnet build -c Release && dotnet pack -c Release`

**Comment by tmds** [comment]
I think the issue may be that `..\Tmds.ExecFunction.VsDebugger\bin\$(Configuration)\$(TargetFramework)\**\*` is a wildcard and when it gets evaluated the file is not there yet.
Can you change to explicitly reference the `Tmds.ExecFunction.VsDebugger.dll` and see if it makes a difference?

**Comment by StratosBlue** [comment]
@tmds 
It seems you are right. I tested `..\Tmds.ExecFunction.VsDebugger\bin\$(Configuration)\$(TargetFramework)\Tmds.ExecFunction.VsDebugger.dll`.  The `dotnet pack` will include `Tmds.ExecFunction.VsDebugger.dll` in the package.

**Comment by tmds** [comment]
Thank you @StratosBlue.
It seems the Travis CI stuff I had setup here is no longer working. I'll get that sorted out.

Could you then verify a NuGet package from the CI feed works for you as expected in Visual Studio?
I don't have a Windows machine, so I can't check myself.

**Comment by tmds** [comment]
I've changed to use GitHub CI. You should now be able to pull a package from the CI feed.

There was a regression. The arguments that configured the debugger in the child were passed on to the child function. Fixed by https://github.com/tmds/Tmds.ExecFunction/commit/fc0a5f4bcffe52a3525763557f949fa2d48c83fa#diff-2ef9e2ec359ca931a16f18f174fc965a4089e2ae92286dd64d66586885a6738d.

**Comment by StratosBlue** [comment]
@tmds 
I hava tested `0.5.1-8-fc0a5f4bcffe52a3525763557f949fa2d48c83fa` with `VisualStudio2022`. It works.

**Comment by tmds** [comment]
Thanks!

This is part of 0.6.0 which was just published to nuget.org.

**Pull request merged**
